In [12]:
import numpy as np
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
a=np.array([[2,4,5],[1,6,3]])
a

array([[2, 4, 5],
       [1, 6, 3]])

In [17]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[-1,5,8],[9,0,7],[19,10,27]])
np.dot(a,b)


array([[ 74,  35, 103],
       [155,  80, 229]])

In [19]:
x=np.array([-3,4,1])
y=np.array([5,2,3])
print(x+10)
print(x*4)
print(x+y)
print(x*y)

[ 7 14 11]
[-12  16   4]
[2 6 4]
[-15   8   3]


In [22]:
from sklearn import datasets
iris=datasets.load_iris()
print(iris.filename)

C:\Users\almra\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv
